const mongoose = require("mongoose");

const paymentSchema = new mongoose.Schema(
  {
    // bookingId: {
    //   type: mongoose.Schema.Types.ObjectId,
    //   ref: "Booking",
    //   required: true,
    // },

    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Booking",
      index: true,
    },

    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    ownerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    propertyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Property",
      required: true,
    },

    amount: {
      type: Number,
      required: true,
    },

    method: {
      type: String,
      enum: ["eSewa", "Khalti"],
      // required: true,
    },

    // transactionId: {    //stores transactionId generated by payment gateway after payment success
    //   type: String,
    //   unique: true,
    //   index:true,
    //   sparse: true, // allows pending payments without transactionId
    // },

    status: {
      type: String,
      enum: ["pending", "confirmed", "rejected", "not received"],
      default: "pending"
    },

    proofImage: {       //optional
      url: String,
      public_id: String
    },

    // paidAt: {
    //   type: Date,
    // },

  },
  { timestamps: true },
);


const Payment = mongoose.model("Payment", paymentSchema);
module.exports = Payment;